program = function_def* BEGIN statement* END
        ;

function_def = FN IDENTIFIER '(' param_list ')' block
             ;

param_list = [ IDENTIFIER { ',' IDENTIFIER } ]
           ;

block = BEGIN statement* END
      ;

statement = if-statement
          | loop-statement
          | while-statement
          | break-statement
          | return-statement
          | assign-statement
          ;

if-statement = IF expression statement* [ ELSE statement* ] END
             ;

loop-statement = LOOP statement* END
               ;

while-statement = WHILE expression statement* END
                ;

break-statement = BREAK
                ;

return-statement = RETURN expression

expression = IDENTIFIER '=' expression
           | eq_comp
           ;

eq_comp = ord_comp [ (==|!=) ord_comp ]
        ;

ord_comp = sum [ (<|<=|>|>=) sum ]
         ;

sum = factor { (+|-) factor }
    ;

factor = term { (*|/|%) term }
       ;

term = IDENTIFIER
     | IDENTIFIER '(' expr_list ')'
     | NUMBER
     | [+|-|!] term
     | '(' expression ')'
     ;

expr_list = [ expression { ',' expression } ]
          ;
