program = BEGIN statement* END
        ;

statement = print-statement
          | read-statement
          | if-statement
          | loop-statement
          | while-statement
          | break-statement
          | assign-statement
          ;

print-statement = PRINT expression
                ;

read-statement = READ IDENTIFIER
               ;

if-statement = IF expression statement* [ ELSE statement* ] END
             ;

loop-statement = LOOP statement* END
               ;

while-statement = WHILE expression statement* END
                ;

break-statement = BREAK
                ;

assign-statement = IDENTIFIER '=' expression
                 ;

expression = ord_comp [ (==|!=) ord_comp ]
           ;

ord_comp = sum [ (<|<=|>|>=) sum ]
         ;

sum = factor { (+|-) factor }
    ;

factor = term { (*|/|%) term }
       ;

term = IDENTIFIER
     | NUMBER
     | [+|-|!] term
     | '(' expression ')'
     ;
